# Site settings
title: Nail Boutique

# contact details
email: info@fake-email.co.za
phone: 555 555 5555
address: 203 Fake St. Mountain View, San Francisco, California, USA

# Opening hours
opening_hours:
  - days: Monday - Friday
    times: 08:00am - 05:00pm
  - days: Saturday - Sunday
    times: 10:00am - 01:00pm

# Social
twitter_username: NailBoutique
facebook_username: NailBoutique
instagram_username: NailBoutique

# Analytics
google_analytics: 

# Build settings
# sass:
#   sass_dir: assets/scss