description: >-
  We may not be able to solve all your problems, but we promise that you leave
  the salon with gorgeous nails.
staff: 
  - name: Candice
    position: Owner
    description: >-
      I'm the owner of Wet Paint Nail Boutique and I've been doing nails for over 11 years.
      I love my job and enjoy every single day! Seeing my client's faces light 
      up when they leave the salon with great looking nails is priceless...
    avatar: /assets/img/candice_avatar.png
  - name: Bullet
    position: Trainee
    description: BORK!
    avatar: /assets/img/bullet_avatar.png