# Max 3
- title: Acrylic Nails
  description: >-
    Nail Boutique only uses the best acrylic products for your nails to insure
    that we keep your natural nails in good condition.
  icon: flaticon-nail
- title: Waxing
  description: >-
    Waxing can be an unpleasant experience, but at Wet Paint Nail Boutique we do our best to
    insure that you are comfortable whether we are waxing your brows or your bikini line.
    Waxing is not a luxury... It's a necessity!
  icon: flaticon-wax
- title: Massages
  description: >-
    If you really want to treat yourself, then a hand or foot massage is the way to go! But
    if you what to walk out the salon feeling like a new person then a relaxing Indian
    head massage will do the trick.
  icon: flaticon-hot-stone