# Max 3
- title: Acrylic Nails
  description: >-
    We only use the best acrylic products for your nails to ensure
    that we maintaing the good health of your natural nails.
  icon: flaticon-nail
- title: Waxing
  description: >-
    Waxing can be an unpleasant experience. We do our best to ensure that you are comfortable,
    whether we are waxing your brows or your bikini line.
    Waxing is not a luxury... It's a necessity!
  icon: flaticon-wax
- title: Massages
  description: >-
    If you really want to treat yourself, then a hand or foot massage is the way to go! But,
    if you walk out feeling like a new person, then a relaxing Indian head massage will do the trick.
  icon: flaticon-hot-stone